import React from 'react';

function Info({ condition }) {
  const diseases = [
    {
      name: "Feline Lower Urinary Track Disease",
      description: "Feline Lower Urinary Tract Disease (FLUTD) encompasses a group of conditions affecting the bladder and urethra in cats. FLUTD is a common and potentially serious health problem in cats, with symptoms ranging from urinary issues and bloody urine to straining during urination. One of the key aspects of managing FLUTD in cats is closely tracking and monitoring their urinary habits and overall well-being. Tracking and monitoring your cat's urinary habits is essential for early detection and management of FLUTD. Keep a close eye on your cat's litter box habits, including the frequency of urination, the volume of urine produced, and any changes in the appearance or odor of the urine. Any deviation from your cat's normal urinary routine, such as increased frequency of urination, straining to urinate, or urinating outside the litter box, should be promptly reported to your veterinarian. In addition to tracking urinary habits, monitoring your cat's water intake can provide valuable insights into their urinary health. Cats with FLUTD may drink more water than usual as their bodies attempt to flush out the urinary system and alleviate discomfort. Keep track of how much water your cat drinks each day and report any significant changes to your veterinarian. Monitoring water intake can help identify potential issues early and guide treatment decisions. Regular veterinary check-ups are also essential for monitoring your cat's urinary health and overall well-being. During these appointments, your veterinarian can perform comprehensive physical exams, assess your cat's urinary system, and conduct diagnostic tests such as urine analysis to evaluate kidney function and screen for urinary tract infections or other abnormalities. These tests can help identify underlying causes of FLUTD and guide treatment decisions to address the root cause of the condition. By actively tracking and monitoring your cat's urinary habits, water intake, and overall well-being, you can play an active role in managing their FLUTD and ensuring they receive the care they need to live a happy, healthy life. Working closely with your veterinarian and following their recommendations for monitoring and treatment can help optimize your cat's urinary health and minimize the risk of complications associated with FLUTD.",
      symptoms: "Urinary issues, frequent urination, bloody urine, straining to urinate",
      commonality: "Fairly common",
      prevention: "Provide plenty of fresh water, feed a balanced diet, maintain litter box hygiene",
      treatment: "Fluid therapy, pain management, dietary changes",
      moreInfo: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/feline-lower-urinary-tract-disease"
    },
    {
      name: "Chronic Kidney Disease",
      description: "Chronic Kidney Disease (CKD) is a progressive condition characterized by the gradual loss of kidney function over time. CKD is one of the most common health problems affecting senior cats, and early detection and management are crucial for preserving kidney function and maintaining your cat's quality of life. One of the key aspects of managing CKD in cats is closely tracking and monitoring their kidney function and overall well-being. Regular monitoring of your cat's kidney function is essential for detecting CKD in its early stages and assessing the progression of the disease over time. Your veterinarian may recommend periodic blood tests to measure levels of creatinine and blood urea nitrogen (BUN), which are waste products that accumulate in the blood when the kidneys are not functioning properly. These tests can help identify changes in kidney function and guide treatment decisions to slow the progression of the disease. In addition to blood tests, monitoring your cat's urine output and quality can provide valuable insights into their kidney health. Keep track of your cat's litter box habits, including the frequency of urination, the volume of urine produced, and any changes in the appearance or odor of the urine. Cats with CKD may produce larger volumes of urine or have dilute urine due to impaired kidney function. Any changes in urinary habits should be promptly reported to your veterinarian for further evaluation. Regular veterinary check-ups are also essential for monitoring your cat's CKD and overall well-being. During these appointments, your veterinarian can perform comprehensive physical exams, assess your cat's hydration status, and monitor changes in body weight or condition. Additional diagnostic tests, such as urine analysis or imaging studies, may be recommended to evaluate kidney function and screen for complications associated with CKD. By actively tracking and monitoring your cat's kidney function, urinary habits, and overall well-being, you can play an active role in managing their CKD and ensuring they receive the care they need to live a happy, comfortable life. Working closely with your veterinarian and following their recommendations for monitoring and treatment can help optimize your cat's kidney health and minimize the progression of CKD.",
      symptoms: "Increased drinking and urination, weight loss, poor appetite, vomiting",
      commonality: "Common in older cats",
      prevention: "Encourage water intake, feed a balanced diet, regular veterinary check-ups",
      treatment: "Fluid therapy, dietary management, medication",
      moreInfo: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/chronic-kidney-disease"
    },
    {
      name: "Hyperthyroidism",
      description: "Hyperthyroidism is a common endocrine disorder in cats, characterized by the overproduction of thyroid hormones by the thyroid glands. This condition typically affects older cats and can have significant impacts on their health and well-being. One of the key aspects of managing Hyperthyroidism in cats is closely tracking and monitoring their thyroid function and overall health. Regular monitoring of thyroid hormone levels is essential for diagnosing Hyperthyroidism in cats and assessing the response to treatment. Your veterinarian may recommend blood tests to measure levels of thyroid hormones, such as thyroxine (T4), to confirm the diagnosis and monitor thyroid function over time. These tests can help identify changes in thyroid hormone levels and guide treatment decisions to normalize thyroid function and alleviate symptoms associated with Hyperthyroidism. In addition to blood tests, monitoring your cat's symptoms and overall well-being can provide valuable insights into the progression of Hyperthyroidism and the effectiveness of treatment. Cats with Hyperthyroidism may exhibit symptoms such as weight loss despite increased appetite, hyperactivity, vomiting, and diarrhea. Keeping track of your cat's behavior, appetite, and body condition can help identify changes that may require adjustments to their treatment plan or additional medical intervention. Regular veterinary check-ups are also essential for monitoring your cat's Hyperthyroidism and overall health. During these appointments, your veterinarian can perform comprehensive physical exams, assess your cat's thyroid glands, and monitor changes in body weight, heart rate, and blood pressure. Additional diagnostic tests, such as thyroid imaging studies or cardiac evaluations, may be recommended to evaluate the extent of thyroid dysfunction and screen for complications associated with Hyperthyroidism. By actively tracking and monitoring your cat's thyroid function, symptoms, and overall well-being, you can play an active role in managing their Hyperthyroidism and ensuring they receive the care they need to live a happy, healthy life. Working closely with your veterinarian and following their recommendations for monitoring and treatment can help optimize your cat's thyroid health and minimize the impact of Hyperthyroidism on their quality of life.",
      symptoms: "Weight loss, increased appetite, vomiting, hyperactivity",
      commonality: "Common in older cats",
      prevention: "Regular veterinary check-ups, monitor thyroid levels",
      treatment: "Medication, radioactive iodine therapy, dietary management",
      moreInfo: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/hyperthyroidism-cats"
    },
    {
      name: "Infammitory Bowel Disease",
      description: "Inflammatory Bowel Disease (IBD) is a chronic gastrointestinal disorder characterized by inflammation of the digestive tract in cats. This condition can affect cats of any age, although it is more commonly diagnosed in middle-aged and senior cats. IBD is a complex disorder that results from an abnormal immune response to dietary antigens or other environmental triggers, leading to inflammation and damage to the lining of the intestines. One of the key aspects of managing IBD in cats is closely tracking and monitoring their gastrointestinal health and overall well-being. Regular monitoring of your cat's gastrointestinal symptoms is essential for diagnosing IBD and assessing the response to treatment. Cats with IBD may exhibit symptoms such as vomiting, diarrhea, weight loss, and poor appetite. Keeping track of your cat's bowel movements, including the frequency, consistency, and presence of blood or mucus, can help identify changes that may indicate worsening inflammation or the need for adjustments to their treatment plan. In addition to monitoring gastrointestinal symptoms, tracking your cat's diet and feeding habits can provide valuable insights into their digestive health and the triggers that may exacerbate their IBD symptoms. Cats with IBD may benefit from a highly digestible, hypoallergenic diet that minimizes exposure to potential dietary triggers. Keeping a detailed log of your cat's food intake, including the type of food, portion sizes, and any treats or supplements given, can help identify dietary factors that may be contributing to their symptoms. Regular veterinary check-ups are also essential for monitoring your cat's IBD and overall health. During these appointments, your veterinarian can perform comprehensive physical exams, assess your cat's gastrointestinal tract, and monitor changes in body weight, hydration status, and nutritional status. Additional diagnostic tests, such as blood tests or imaging studies, may be recommended to evaluate the extent of inflammation and screen for complications associated with IBD. By actively tracking and monitoring your cat's gastrointestinal symptoms, diet, and overall well-being, you can play an active role in managing their IBD and ensuring they receive the care they need to live a happy, comfortable life. Working closely with your veterinarian and following their recommendations for monitoring and treatment can help optimize your cat's gastrointestinal health and minimize the impact of IBD on their quality of life.",
      symptoms: "Vomiting, diarrhea, weight loss, poor appetite",
      commonality: "Can affect cats of any age",
      prevention: "Feed a high-quality diet, avoid sudden diet changes",
      treatment: "Dietary management, medication, probiotics",
      moreInfo: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/inflammatory-bowel-disease"
    },
    {
      name: "Diabetes Mellitus",
      description: "Diabetes Mellitus is a metabolic disorder characterized by high blood sugar levels in cats. It is a complex condition that results from either insufficient insulin production or an inability of the body's cells to respond effectively to insulin. One of the key aspects of managing Diabetes Mellitus in cats is closely monitoring their condition through regular tracking of blood glucose levels and other relevant parameters. Tracking and monitoring your cat's health can play a crucial role in managing Diabetes Mellitus effectively. Regular monitoring of blood glucose levels allows pet owners and veterinarians to assess how well the cat's diabetes is controlled and whether any adjustments to treatment are necessary. This is typically done using a handheld glucometer, which measures blood glucose levels from a small sample of blood obtained through a pinprick on the cat's ear or paw. In addition to monitoring blood glucose levels, tracking other parameters such as food intake, water consumption, and urination frequency can provide valuable insights into the cat's overall health and diabetes management. Keeping a detailed log of these factors can help identify patterns or trends that may indicate changes in the cat's condition or response to treatment. For example, increased water consumption and urination may signal inadequate blood sugar control or the presence of complications such as urinary tract infections. Regular veterinary check-ups are also essential for monitoring your cat's diabetes and overall health. During these appointments, your veterinarian can perform comprehensive physical exams, assess your cat's response to treatment, and conduct additional tests such as blood tests or urine analysis to evaluate kidney function and screen for complications associated with diabetes. In addition to tracking physical parameters, it's important to monitor your cat's behavior and overall well-being. Cats with uncontrolled diabetes may exhibit symptoms such as lethargy, weakness, decreased appetite, or changes in litter box habits. Any changes in behavior or symptoms should be promptly reported to your veterinarian, as they may indicate the need for adjustments to the cat's treatment plan or additional medical intervention. By actively tracking and monitoring your cat's condition, you can play an active role in managing their diabetes and ensuring they receive the care they need to live a happy, healthy life. Working closely with your veterinarian and following their recommendations for monitoring and treatment can help optimize your cat's diabetes management and minimize the risk of complications associated with the disease.",
      symptoms: "Increased drinking and urination, weight loss, lethargy",
      commonality: "Increasing in prevalence",
      prevention: "Maintain healthy weight, feed a balanced diet",
      treatment: "Insulin therapy, dietary management, weight management",
      moreInfo: "https://www.vet.cornell.edu/departments/cornell-feline-health-center/health-information/feline-health-topics/feline-diabetes"
    },
    {
      name: "Feline Obesity",
      description: "Feline obesity is a prevalent and serious health concern affecting cats of all ages, breeds, and lifestyles. It occurs when a cat's body weight exceeds the ideal range for their breed and size due to an imbalance between calorie intake and energy expenditure. Obesity can have significant negative impacts on a cat's health, increasing the risk of various medical conditions such as diabetes mellitus, osteoarthritis, and cardiovascular disease. One of the key aspects of managing feline obesity is closely tracking and monitoring your cat's weight, diet, and activity levels. Regular monitoring of your cat's weight is essential for detecting and managing obesity early on. Keep track of your cat's body condition score, which evaluates their overall body condition based on factors such as body shape, rib palpation, and waist definition. Your veterinarian can assess your cat's body condition score during regular check-ups and provide guidance on achieving and maintaining a healthy weight through dietary management and lifestyle changes. Tracking your cat's diet and feeding habits is crucial for addressing the underlying causes of obesity and promoting weight loss. Cats with obesity may benefit from a balanced, calorie-controlled diet that provides adequate nutrition without excess calories. Keep a detailed log of your cat's daily food intake, including the type of food, portion sizes, and any treats or supplements given. Monitoring your cat's food intake can help identify areas where adjustments may be needed to promote weight loss and improve overall health. In addition to tracking diet, monitoring your cat's activity levels and exercise habits can play a vital role in managing obesity. Encourage regular physical activity through interactive play sessions, environmental enrichment, and access to toys or climbing structures. Keep track of your cat's activity levels and encourage gradual increases in exercise over time. Regular exercise not only helps burn calories but also promotes muscle tone, joint health, and mental stimulation. Regular veterinary check-ups are also essential for monitoring your cat's obesity and overall health. During these appointments, your veterinarian can perform comprehensive physical exams, assess your cat's weight and body condition, and screen for obesity-related complications such as diabetes or joint problems. Your veterinarian can also provide personalized recommendations for weight management and monitor your cat's progress over time to ensure successful weight loss and improved health outcomes. By actively tracking and monitoring your cat's weight, diet, activity levels, and overall well-being, you can play an essential role in managing their obesity and promoting a healthier lifestyle. Working closely with your veterinarian and following their recommendations for tracking and monitoring can help achieve sustainable weight loss and improve your cat's quality of life in the long term.",
      symptoms: "Weight gain, lethargy, difficulty breathing",
      commonality: "Increasing in prevalence",
      prevention: "Feed controlled portions, encourage exercise",
      treatment: "Dietary management, increased physical activity",
      moreInfo: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/obesity"
    }
  ];

  const disease = diseases.find(d => d.name === condition);

  if (!disease) {
    return <div>No information available for this condition.</div>;
  }

  return (
    <div className="max-w-2xl mx-auto">
      <h1 className="text-2xl font-bold mb-4 pt-8">{disease.name}</h1>
      <p className="text-lg mb-2">{disease.description}</p>
      <p className="mb-2"><strong>Symptoms:</strong> {disease.symptoms}</p>
      <p className="mb-2"><strong>Commonality:</strong> {disease.commonality}</p>
      <p className="mb-2"><strong>Prevention:</strong> {disease.prevention}</p>
      <p className="mb-2"><strong>Treatment:</strong> {disease.treatment}</p>
      <p className="mb-2">To learn more about {disease.name}, <a href={disease.moreInfo} target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">click here</a>.</p>
    </div>
  );
}

export default Info;


